/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import SCHEDULING.CSCAN;
import SCHEDULING.FIFO;
import SCHEDULING.NSCAN;
import SCHEDULING.RANDOM;
import SCHEDULING.SCAN;
import SCHEDULING.SSTF;
import UTIL.Control;
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.LinkedList;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


/**
 *
 * @author Erin
 */
public class Grafico extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */
    public Grafico() {
        initUI();
        initComponents();
    }
    
//     public Grafico(String algoritmo) {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initUI() {
                          
        XYDataset dataset = createDataset();
        JFreeChart chart = createChart(dataset);
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        chartPanel.setBackground(Color.white);
        add(chartPanel);
//        JPanel jPanel = new JPanel();
//        jPanel.add(chartPanel); //add the chart viewer to the JPanel


        pack();
        setTitle("Disk scheduling");
        setLocationRelativeTo(null);
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
   
    private XYDataset createDataset() {
        int tiempo = 0;
        
        //XYSeries series = new XYSeries("Secuencia de pistas visitadas");
        XYSeries series1 = new XYSeries("C-SCAN");
        XYSeries series2 = new XYSeries("FIFO");
        XYSeries series3 = new XYSeries("LIFO");
        XYSeries series4 = new XYSeries("F-SCAN");
        XYSeries series5 = new XYSeries("N-SCAN");
        XYSeries series6 = new XYSeries("PRIORIDAD");
        XYSeries series7 = new XYSeries("RANDOM");
        XYSeries series8 = new XYSeries("SCAN");
        XYSeries series9 = new XYSeries("SSTF");
    

        Integer[] arrayCSCAN = Control.sstfTracks.toArray(new Integer[Control.sstfTracks.size()]);
        Integer[] arrayFIFO = Control.fifoTracks.toArray(new Integer[Control.fifoTracks.size()]);
        Integer[] arrayLIFO = Control.lifoTracks.toArray(new Integer[Control.lifoTracks.size()]);
        Integer[] arrayFSCAN = Control.fscanTracks.toArray(new Integer[Control.fscanTracks.size()]);
        Integer[] arrayNSCAN = Control.nscanTracks.toArray(new Integer[Control.nscanTracks.size()]);
        Integer[] arrayPRI = Control.prioridadTracksEstadisticas.toArray(new Integer[Control.prioridadTracksEstadisticas.size()]);
        Integer[] arrayRAM = Control.randomTracks.toArray(new Integer[Control.randomTracks.size()]);
        Integer[] arraySCAN = Control.scanTracks.toArray(new Integer[Control.scanTracks.size()]);
        Integer[] arraySSTF = Control.sstfTracks.toArray(new Integer[Control.sstfTracks.size()]);
      
        for (Integer array1 : arrayCSCAN) {
            series1.add(tiempo, array1);
            tiempo = tiempo + 5;
        }
        tiempo = 0;
        for (Integer array2 : arrayFIFO) {
            //tiempo = 0;
            series2.add(tiempo, array2);
            tiempo = tiempo + 5;
        }
        tiempo = 0;
        for (Integer array3 : arrayLIFO) {
            //tiempo = 0;
            series3.add(tiempo, array3);
            tiempo = tiempo + 5;
        }
        tiempo = 0;
        for (Integer array4 : arrayFSCAN) {
            //
            series4.add(tiempo, array4);
            tiempo = tiempo + 5;
        }
        tiempo = 0;
        for (Integer array5 : arrayNSCAN) {
            //
            series5.add(tiempo, array5);
            tiempo = tiempo + 5;
        }
        tiempo = 0;
        for (Integer array6 : arrayPRI) {
            //tiempo = 0;
            series6.add(tiempo, array6);
            tiempo = tiempo + 5;
        }
        tiempo = 0;
        for (Integer array7 : arrayRAM) {
            
            series7.add(tiempo, array7);
            tiempo = tiempo + 5;
        }
        tiempo = 0;
        for (Integer array8 : arraySCAN) {
            
            series8.add(tiempo, array8);
            tiempo = tiempo + 5;
        }
        tiempo = 0;
        for (Integer array9 : arraySSTF) {
            
            series9.add(tiempo, array9);
            tiempo = tiempo + 5;
        }
       
        XYSeriesCollection dataset = new XYSeriesCollection();
        //dataset.addSeries(series);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        dataset.addSeries(series3);
        dataset.addSeries(series4);
        dataset.addSeries(series5);
        dataset.addSeries(series6);
        dataset.addSeries(series7);
        dataset.addSeries(series8);
        dataset.addSeries(series9);

        return dataset;
    }

    private JFreeChart createChart(XYDataset dataset) {

        JFreeChart chart = ChartFactory.createXYLineChart(
                "Disk scheduling", 
                "Time", 
                "Track nnumber", 
                dataset, 
                PlotOrientation.VERTICAL,
                true, 
                true, 
                false 
        );
      

        XYPlot plot = chart.getXYPlot();

        
    
        XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();
        renderer.setSeriesPaint(0, Color.RED);
        renderer.setSeriesStroke(0, new BasicStroke(2.0f));
        
        // sets paint color for plot outlines
        plot.setOutlinePaint(Color.BLACK);
        plot.setOutlineStroke(new BasicStroke(2.0f));


        plot.setRenderer(renderer);
        plot.setBackgroundPaint(Color.white);

        plot.setRangeGridlinesVisible(true);
        plot.setRangeGridlinePaint(Color.BLACK);

        plot.setDomainGridlinesVisible(true);
        plot.setDomainGridlinePaint(Color.BLACK);

        chart.getLegend().setFrame(BlockBorder.NONE);

        chart.setTitle(new TextTitle("Disk Scheduling Algorithms",
                        new Font("Serif", java.awt.Font.BOLD, 18)));
               
        return chart;

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                
        Control.leerArchivo();
//        SSTF sstf = new SSTF();
//        sstf.start();
//        NSCAN nscan = new NSCAN();
//        nscan.start();
                    //fillAverageNSCAN();
        
        SCAN scan = new SCAN();
        scan.start();
                    
//        FIFO fifo = new FIFO();
//        fifo.start();
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
